/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 tyrannosarus_rex_free_model.glb -T --shadows
Author: Joel Anderson (https://sketchfab.com/joel3d)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/tyrannosarus-rex-free-model-e18c433cdd1c49f8ac152348b7384037
Title: Tyrannosarus rex (Free model)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {angleToRadians} from "@/utils/angle";

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/dragon/scene.glb')
  return (
    <group {...props} dispose={null} scale={0.2} position={[4, 0, -3]} rotation={[0,0,0]}>>
      <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.SkinColor} />
      <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.eyeColor} />
      <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.blackMatteColor} />
      <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.eyeTransparentColor} />
      <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials.teethTexture} />
      <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.clawColor} />
    </group>
  )
}

useGLTF.preload('/models/dragon/scene.glb')
